on:
  workflow_call:
    outputs:
      otpVersion:
        description: "The .tool-versions OTP version"
        value: "${{ jobs.detectToolVersions.outputs.otpVersion }}"
      elixirVersion:
        description: "The .tool-versions Elixir version"
        value: "${{ jobs.detectToolVersions.outputs.elixirVersion }}"

name: "Detect Tool Versions"

jobs:
  detectToolVersions:
    name: "Detect Tool Versions"

    runs-on: ubuntu-latest

    outputs:
      otpVersion: "${{ env.OTP_VERSION }}"
      elixirVersion: "${{ env.ELIXIR_VERSION }}"

    steps:
      - uses: actions/checkout@v4
      - name: "Read .tool-versions"
        id: toolVersions
        run: |
          OTP_VERSION="$(cat .tool-versions | grep erlang | cut -d' ' -f2-)"
          echo OTP: $OTP_VERSION
          echo "OTP_VERSION=${OTP_VERSION}" >> $GITHUB_ENV

          ELIXIR_VERSION="$(cat .tool-versions | grep elixir | cut -d' ' -f2-)"
          echo Rebar: $ELIXIR_VERSION
          echo "ELIXIR_VERSION=${ELIXIR_VERSION}" >> $GITHUB_ENV
