on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

name: "Stable Tag"

jobs:
  detectToolVersions:
    name: "Detect Tool Versions"

    uses: ./.github/workflows/part_tool_versioning.yml

  release:
    name: "Release"

    uses: ./.github/workflows/part_release.yml
    with:
      releaseName: "${{ github.ref_name }}"
      stable: true

  docs:
    name: "Docs"

    needs: ["release", "detectToolVersions"]

    uses: ./.github/workflows/part_docs.yml
    with:
      otpVersion: "${{ needs.detectToolVersions.outputs.otpVersion }}"
      elixirVersion: "${{ needs.detectToolVersions.outputs.elixirVersion }}"
      releaseName: "${{ github.ref_name }}"
